_wandb:
    value:
        cli_version: 0.21.1
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
            "4": 3.8.20
            "5": 0.21.1
            "12": 0.21.1
            "13": linux-x86_64
