map_name: corridor
state_type: FP # choose from FP (Feature Pruned) and EP (Environment Provided)
# Options:
# 3m - easy
# 8m - easy
# 25m - hard
# 5m_vs_6m - hard
# 8m_vs_9m - hard
# 10m_vs_11m - easy
# 27m_vs_30m - superhard
# MMM - easy
# MMM2 - superhard
# 2s3z - easy
# 3s5z - hard
# 3s5z_vs_3s6z - superhard
# 3s_vs_3z - easy
# 3s_vs_4z - easy
# 3s_vs_5z - hard
# 1c3s5z - easy
# 2m_vs_1z - easy
# corridor - superhard
# 6h_vs_8z - superhard
# 2s_vs_1sc - easy
# so_many_baneling - easy
# bane_vs_bane - hard
# 2c_vs_64zg - hard

# heterogeneous setting
# 2s3z
# 3s5z
# MMM
# 3s5z_vs_3s6z
# MMM2
# 1c3s5z